import './globals.css'
import {Figtree} from 'next/font/google'
import React from "react";
import Sidebar from "@/components/Sidebar";
import SupabaseProvider from "@/providers/SupabaseProvider";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import getSongsByUserid from "@/actions/getSongsByUserid";
import Player from "@/components/Player";
import getActiveProductsWithPrices
    from "@/actions/getActiveProductsWithPrices";

const font = Figtree({subsets: ['latin']})

export const metadata = {
    title: 'Spotify~ish',
    description: 'Generated by create next app',
}
export const revalidate = 0;

export default  async function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    const userSongs = await getSongsByUserid();
    const products = await getActiveProductsWithPrices();



    return (
        <html lang="en">
        <body className={font.className}>
        <ToasterProvider/>
        <SupabaseProvider>
            <UserProvider>
                <ModalProvider products={products}/>
                <Sidebar songs={userSongs}>
                    {children}
                </Sidebar>
                <Player />
            </UserProvider>
        </SupabaseProvider>
        </body>
        </html>
    )
}
